### PR TITLE
Update SCREENSHOTSDISPLAY.md

### PR DESCRIPTION
**Pull request by antun0**

### CODE REVIEW

**Comment by EzioTheDeadPoet** [comment]
Do you by chance have a higher resolution screenshot, of did you play at 640x360 ? (Not trying to be rude just want to make sure the right image is uploaded/put on display, if you only have the 640x360 resolution one and played at that resolution than this is totally fine, it just feels odd to me, that's all.)

**Comment by antun0** [comment]
No I'm playing at 1920x1080. Don't know why it would have gone for a 640x360 resolution.

**Comment by EzioTheDeadPoet** [comment]
what tool did you use to take the shot ?
or do you maybe have different versions of the Screenshot ?
Also check if maybe imgur resized your image.

**Comment by antun0** [comment]
I took it with shadowplay and I have it saved at 1080p on my computer.

**Comment by EzioTheDeadPoet** [comment]
I would recommend trying a reupload then (you then can edit the file here to update the link so you don't have to do another pull request.)

**Comment by antun0** [comment]
Should be reuploaded now.

**Comment by EzioTheDeadPoet** [comment]
sorry my bad I just realized that imgur resizes images when viewed on mobile for some reason, so sorry for the inconvenience🙈🙈

**Comment by antun0** [comment]
Haha it's fine. Just happy to share a screenshot! :)

**Pull request merged**
